import { computed } from 'vue'
import type { 
  ConnectionSnapshot, 
  IpApiResponse,
  BrowserInfo,
  DeviceInfo,
  ScreenInfo,
  WindowInfo,
  ConnectionInfo,
  StorageInfo,
  FeatureSupport,
  FingerprintingInfo,
  PermissionsInfo,
  MediaInfo,
  BatteryInfo,
  BluetoothInfo,
  InputInfo,
  RiskInfo,
  PerformanceTiming,
  // NEW types
  WebRTCLeakInfo,
  WebSocketConnectivity,
  IPv6Connectivity,
  DeviceMemoryInfo,
  VRInfo,
  GamepadInfo,
  WakeLockInfo,
  ContactPickerInfo,
  FileSystemAccessInfo,
  PictureInPictureInfo,
  PaymentRequestInfo,
  CredentialManagementInfo,
  ExtendedScreenInfo,
  UserPreferences,
  ShareApiInfo,
  TlsInfo,
  PageVisibilityInfo
} from '@/types'

export function useSnapshotBuilder(
  ipInfo: { value: IpApiResponse | null },
  browserInfo: { value: BrowserInfo },
  deviceInfo: { value: DeviceInfo },
  screenInfo: { value: ScreenInfo },
  windowInfo: { value: WindowInfo },
  connectionInfo: { value: ConnectionInfo },
  storageInfo: { value: StorageInfo },
  featureSupport: { value: FeatureSupport },
  fingerprintingInfo: { value: FingerprintingInfo },
  permissionsInfo: { value: PermissionsInfo },
  mediaInfo: { value: MediaInfo },
  batteryInfo: { value: BatteryInfo },
  bluetoothInfo: { value: BluetoothInfo },
  inputInfo: { value: InputInfo },
  riskInfo: { value: RiskInfo },
  performanceTiming: { value: PerformanceTiming | null },
  // NEW parameters
  webRTCLeak: { value: WebRTCLeakInfo | null },
  webSocketConnectivity: { value: WebSocketConnectivity },
  ipv6Connectivity: { value: IPv6Connectivity },
  deviceMemory: { value: DeviceMemoryInfo },
  vrInfo: { value: VRInfo },
  gamepadInfo: { value: GamepadInfo },
  wakeLock: { value: WakeLockInfo },
  contactPicker: { value: ContactPickerInfo },
  fileSystemAccess: { value: FileSystemAccessInfo },
  pictureInPicture: { value: PictureInPictureInfo },
  paymentRequest: { value: PaymentRequestInfo },
  credentialManagement: { value: CredentialManagementInfo },
  extendedScreen: { value: ExtendedScreenInfo },
  userPreferences: { value: UserPreferences },
  shareApi: { value: ShareApiInfo },
  tlsInfo: { value: TlsInfo },
  pageVisibilityInfo: { value: PageVisibilityInfo }
) {
  const snapshot = computed<ConnectionSnapshot>(() => ({
    ip: ipInfo.value,
    browser: browserInfo.value,
    device: deviceInfo.value,
    screen: screenInfo.value,
    window: windowInfo.value,
    connection: connectionInfo.value,
    storage: storageInfo.value,
    features: featureSupport.value,
    fingerprinting: fingerprintingInfo.value,
    permissions: permissionsInfo.value,
    media: mediaInfo.value,
    battery: batteryInfo.value,
    bluetooth: bluetoothInfo.value,
    input: inputInfo.value,
    risk: riskInfo.value,
    performance: performanceTiming.value,
    // NEW fields
    webRTCLeak: webRTCLeak.value,
    webSocketConnectivity: webSocketConnectivity.value,
    ipv6Connectivity: ipv6Connectivity.value,
    deviceMemory: deviceMemory.value,
    vrInfo: vrInfo.value,
    gamepadInfo: gamepadInfo.value,
    wakeLock: wakeLock.value,
    contactPicker: contactPicker.value,
    fileSystemAccess: fileSystemAccess.value,
    pictureInPicture: pictureInPicture.value,
    paymentRequest: paymentRequest.value,
    credentialManagement: credentialManagement.value,
    extendedScreen: extendedScreen.value,
    userPreferences: userPreferences.value,
    shareApi: shareApi.value,
    meta: {
      generatedAt: new Date().toISOString()
    }
  }))
  
  return {
    snapshot
  }
}
