import type { ConnectionSnapshot } from '@/types'

export type ExportFormat = 'json' | 'csv' | 'markdown'

export async function copyTextToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text)
      return true
    } else {
      const textarea = document.createElement('textarea')
      textarea.value = text
      textarea.style.position = 'fixed'
      textarea.style.opacity = '0'
      document.body.appendChild(textarea)
      textarea.select()
      const success = document.execCommand('copy')
      document.body.removeChild(textarea)
      return success
    }
  } catch {
    return false
  }
}

export function downloadJson(data: unknown, filename?: string): void {
  const blob = new Blob([JSON.stringify(data, null, 2)], {
    type: 'application/json'
  })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  const stamp = new Date().toISOString().replace(/[:.]/g, '-')
  a.href = url
  a.download = filename || `connection-inspector-${stamp}.json`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function downloadCsv(data: ConnectionSnapshot, filename?: string): void {
  const rows: string[][] = [
    ['Category', 'Property', 'Value'],
    ['IP', 'Address', data.ip?.ip ?? 'Unknown'],
    ['IP', 'Country', data.ip?.location?.country ?? 'Unknown'],
    ['IP', 'City', data.ip?.location?.city ?? 'Unknown'],
    ['IP', 'ASN', data.ip?.asn?.asn?.toString() ?? 'Unknown'],
    ['IP', 'Organization', data.ip?.asn?.org ?? 'Unknown'],
    ['Browser', 'Name', data.browser.browserName ?? 'Unknown'],
    ['Browser', 'Version', data.browser.browserVersion ?? 'Unknown'],
    ['Browser', 'Engine', data.browser.browserEngine ?? 'Unknown'],
    ['Browser', 'User Agent', data.browser.userAgent ?? 'Unknown'],
    ['Device', 'Type', data.device.type ?? 'Unknown'],
    ['Device', 'OS', data.device.osName ?? 'Unknown'],
    ['Device', 'OS Version', data.device.osVersion ?? 'Unknown'],
    ['Screen', 'Width', data.screen.width?.toString() ?? 'Unknown'],
    ['Screen', 'Height', data.screen.height?.toString() ?? 'Unknown'],
    [
      'Screen',
      'Pixel Ratio',
      data.screen.devicePixelRatio != null
        ? (Math.round(data.screen.devicePixelRatio * 100) / 100).toString()
        : 'Unknown'
    ],
    ['Risk', 'Score', data.risk.score?.toString() ?? 'Unknown'],
    ['Risk', 'Band', data.risk.band ?? 'Unknown'],
    ['Connection', 'Transport', data.connection.type ?? 'Unknown'],
    ['Connection', 'Effective Type', data.connection.effectiveType ?? 'Unknown'],
    [
      'Connection',
      'Downlink Mbps',
      data.connection.downlink != null ? String(data.connection.downlink) : 'Unknown'
    ],
    ['Connection', 'RTT ms', data.connection.rtt != null ? String(data.connection.rtt) : 'Unknown']
  ]

  const csvContent = rows
    .map(row => row.map(cell => `"${cell.replace(/"/g, '""')}"`).join(','))
    .join('\n')
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  const stamp = new Date().toISOString().replace(/[:.]/g, '-')
  a.href = url
  a.download = filename || `connection-inspector-${stamp}.csv`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function generateMarkdown(data: ConnectionSnapshot): string {
  const lines: string[] = [
    '# Connection Inspector Report',
    '',
    `Generated: ${new Date().toISOString()}`,
    '',
    '## Network & IP',
    '',
    `- **IP Address:** ${data.ip?.ip ?? 'Unknown'}`,
    `- **Location:** ${data.ip?.location?.city ?? 'Unknown'}, ${data.ip?.location?.country ?? 'Unknown'}`,
    `- **ASN:** ${data.ip?.asn?.asn ?? 'Unknown'}`,
    `- **Organization:** ${data.ip?.asn?.org ?? 'Unknown'}`,
    `- **Risk Score:** ${data.risk.score ?? 'Unknown'}/100 (${data.risk.band ?? 'Unknown'})`,
    '',
    '## Browser',
    '',
    `- **Name:** ${data.browser.browserName ?? 'Unknown'}`,
    `- **Version:** ${data.browser.browserVersion ?? 'Unknown'}`,
    `- **Engine:** ${data.browser.browserEngine ?? 'Unknown'}`,
    `- **Platform:** ${data.browser.platform ?? 'Unknown'}`,
    `- **Languages:** ${data.browser.languages.join(', ') || 'Unknown'}`,
    '',
    '## Device',
    '',
    `- **Type:** ${data.device.type ?? 'Unknown'}`,
    `- **OS:** ${data.device.osName ?? 'Unknown'} ${data.device.osVersion ?? ''}`,
    `- **Screen:** ${data.screen.width ?? 'Unknown'}x${data.screen.height ?? 'Unknown'} @ ${
      data.screen.devicePixelRatio != null
        ? Math.round(data.screen.devicePixelRatio * 100) / 100
        : 1
    }x`,
    `- **Hardware Cores:** ${data.screen.hardwareConcurrency ?? 'Unknown'}`,
    '',
    '---',
    '*Generated by Connection Inspector*'
  ]

  return lines.join('\n')
}

export function buildDebugSnippet(snapshot: ConnectionSnapshot): string {
  const ip = snapshot.ip?.ip ?? 'Unknown IP'
  const locParts: string[] = []
  if (snapshot.ip?.location?.city) locParts.push(snapshot.ip.location.city)
  if (snapshot.ip?.location?.state) locParts.push(snapshot.ip.location.state)
  if (snapshot.ip?.location?.country) locParts.push(snapshot.ip.location.country)
  const location = locParts.join(', ') || 'Unknown location'

  const asn = snapshot.ip?.asn?.asn != null ? `AS${snapshot.ip.asn.asn}` : 'Unknown ASN'
  const org = snapshot.ip?.asn?.org ?? snapshot.ip?.company?.name ?? 'Unknown org'

  const riskFlags: string[] = []
  if (snapshot.ip?.is_tor) riskFlags.push('Tor')
  if (snapshot.ip?.is_vpn) riskFlags.push('VPN')
  if (snapshot.ip?.is_proxy) riskFlags.push('Proxy')
  if (snapshot.ip?.is_datacenter) riskFlags.push('Datacenter')
  if (snapshot.ip?.is_bogon) riskFlags.push('Bogon')

  const riskLine = riskFlags.length ? riskFlags.join(', ') : 'None reported'

  const browserLine = snapshot.browser.userAgent || 'Unknown browser'

  const screenLine =
    snapshot.screen.width && snapshot.screen.height
      ? `${snapshot.screen.width}x${snapshot.screen.height} @ ${
          snapshot.screen.devicePixelRatio != null
            ? Math.round(snapshot.screen.devicePixelRatio * 100) / 100
            : 1
        }x`
      : 'Unknown'

  const parts = [
    `IP: ${ip} (${location})`,
    `ASN/Org: ${asn} • ${org}`,
    `Risk flags: ${riskLine} • Gauge: ${snapshot.risk.band} (${snapshot.risk.score ?? 'n/a'}/100)`,
    `Browser: ${browserLine}`,
    `Screen: ${screenLine}`,
    `Timezone: ${snapshot.browser.timezone ?? 'Unknown'} • Languages: ${snapshot.browser.languages.join(', ') || 'Unknown'}`,
    `Generated at: ${new Date().toISOString()}`
  ]

  return parts.join('\n')
}
